# Generated by Django 6.0 on 2025-12-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TasksApp", "0002_alter_task_description_member_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
